import './components/habit-list.js'
import './components/habit.js'
import './components/heading.js'
import './components/icon.js'
import './components/list.js'
import './components/nav.js'
import './components/progress.js'
import './pages/home.js'
